# frozen_string_literal: true

User.create!(email: 'admin@admin.com', password: '123', is_admin: true)
User.create!({ password: 'test', email: 'test@gmail.com' })
User.create!({ password: 'test2', email: 'test2@gmail.com' })
User.create!({ password: 'test3', email: 'test2@gmail.com' })
User.create!({ password: 'test4', email: 'a4@gmail.com' })
Post.create!(content: 'First Post', body: 'test posts', author: User.first)
Post.create!(content: 'Second Post', body: 'test posts', author: User.first)
Post.create!(content: 'ABC', body: 'test posts', author: User.second)
Post.create!(content: 'DGH Post', body: 'test posts', author: User.second)
Profile.create!(address: 'Ha Noi', telephone: '0123456789', age: '', name: 'Le Tai', hobby: 'Game', user: User.first)
Profile.create!(address: 'Ha Tay', telephone: '0123456729', age: '22', name: 'Tu', hobby: 'Game', user: User.second)
Profile.create!(address: 'Ha Tay', telephone: '0123456729', age: '22', name: 'Phong', hobby: 'Game', user: User.third)
Profile.create!(address: 'Ha Tay', telephone: '0123456729', age: '22', name: 'Hai', hobby: 'Game', user: User.fourth)
Event.create!(content: 'Tat nien 2022', body: 'All memmber')
Event.create!(content: 'Quoc khanh 30/4', body: 'All memmber')
Enrollment.create!(user: User.first, event: Event.first, content: 'Ban to chuc')
Card.create!(user: User.first, number: '1231314123')
BankInfo.create!(card: User.first.card, name: 'Vietinbank', open_at: 'Hai Ba Trung', branch: 'Ha Noi')
Comment.create!(body: 'hihi', commentable: Post.first, user: User.first)
Comment.create!(body: 'Chaha', commentable: Post.first, user: User.second)
Comment.create!(body: 'Event vui', commentable: Event.first, user: User.second)
